[package]

name = "offscreen_gl_context"
version = "0.0.1"
authors = ["ecoal95 <ecoal95@gmail.com>"]

[features]
texture_surface = ["layers"]

[dependencies]
libc = "*"
log  = "*"

[dependencies.glx]
git = "https://github.com/servo/rust-glx"

[dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[dependencies.cgl]
git = "https://github.com/servo/rust-cgl"

[dependencies.gleam]
git = "https://github.com/servo/gleam"

[dependencies.geom]
git = "https://github.com/servo/rust-geom"

[dependencies.core_foundation]
git = "https://github.com/servo/rust-core-foundation"

[dependencies.layers]
git = "https://github.com/servo/rust-layers"
optional = true
