[package]
name = "offscreen_gl_context"
license = "MIT / Apache-2.0"
version = "0.14.2"
authors = ["Emilio Cobos Álvarez <emilio@crisal.io>", "The Servo Project Developers"]
description = "Creation and manipulation of HW accelerated offscreen rendering contexts in multiple platforms. Originally intended for the Servo project's WebGL implementation."
repository = "https://github.com/emilio/rust-offscreen-rendering-context"
build = "build.rs"

[build-dependencies]
gl_generator = "0.8"

[features]
default = ["x11"]
osmesa = ["osmesa-sys"]
# NOTE: Just for testing use, there are no other changes
test_egl_in_linux = ["libloading", "lazy_static"]

[dependencies]
log  = "0.3"
gleam = "0.4.10"
euclid = "0.16"
serde = { version = "1.0", optional = true }
osmesa-sys = { version = "0.1", optional = true }
libloading = { version = "0.4", optional = true, default-features = false }
lazy_static = { version = "1", optional = true }

[target.x86_64-apple-darwin.dependencies]
core-foundation = "0.5"
cgl = "0.2"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"
libloading = { version = "0.4", default-features = false }

[target.'cfg(all(unix, not(any(target_os = "macos", target_os = "android", target_os = "ios"))))'.dependencies.x11]
optional = true
version = "2.3.0"
features = ["xlib"]

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["wingdi", "winuser", "libloaderapi"] }

[target.'cfg(any(target_os="macos", target_os="windows", target_os="android", target_os="ios"))'.dependencies]
lazy_static = "1"

[target.'cfg(target_os = "android")'.dependencies]
libloading = { version = "0.4", default-features = false }
